[CI AUTO] Updating shared files for all packages.
Had an issue where automatic test triggers began before PyPI had managed the new package version.
To combat this I'm having a check re-run 10 times with 5 seconds interval to check the package versions on PyPI.

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -72,7 +72,12 @@ jobs:
 
       - name: Run unittests
         run: |
-          python -m unittest discover ${{ github.event.repository.name }}/test
+          result=$(python -m unittest discover ${{ github.event.repository.name }}/test 2>&1)
+          if [[ $result == *"Ran 0 tests"* ]]; then
+          echo "FAILING: Couldn't find any tests"
+          exit 1
+          fi
+          echo $result
 
 
   publisher:
@@ -153,6 +158,7 @@ jobs:
           pypi_versions=$(pip install ${{ github.event.repository.name }}== 2>&1) || :
           if [[ $pypi_versions == *"${{ env.NEW_VERSION }}"* ]]; then
           found_version=1
+          echo "Found new verson on PyPI!"
           break
           fi
           echo "Couldn't find new version on PyPI, trying again in 5 seconds"
